### PR TITLE
fixes AoT function lookup

### LINKED ISSUE #146: AoT compiled function dependencies don't show up
```clojure
(fn-deps reverse)
;; => #{}
;; expected:
;; => #{#clojure.core/reduce1 #clojure.core/conj}
```

This is because the AoT code is not loaded by Clojures `DynamicClassLoader`. 
I've got a fix for some of this in a bit.
The harder problem is that some functions, like `map` inherit from `clojure.lang.RestFn` and do not have references to their dependencies. I'm still investigating if we can somehow cover those.

### PR DESCRIPTION
**Pull request by Cyrik**
Fixes #146

Before submitting a PR make sure the following things have been done:

- [x] The commits are consistent with our [contribution guidelines](../blob/master/.github/CONTRIBUTING.md)
- [x] You've added tests to cover your change(s)
- [x] All tests are passing
- [x] The new code is not generating reflection warnings
- [ ] You've updated the [changelog](../blob/master/CHANGELOG.md) (if adding/changing user-visible functionality)

Thanks!

### CODE REVIEW

File: src/orchard/xref.clj [hunk 1]
```diff
@@ -57,13 +57,18 @@
...
+    (let [f-class-name (-> v .getClass .getName)
+          ;; this uses the implementation detail that the clojure compiler always
+          ;; prefixes names of lambdas with the name of its surrounding function class
+          deps (into #{} (comp (filter (fn [[k _v]] (clojure.string/includes? k f-class-name)))
+                               (map (fn [[_k value]] (.get ^java.lang.ref.Reference value)))
+                               (mapcat fn-deps-class))
+                     class-cache)]
+      ;; if there's no deps the class is most likely AoT compiled,
+      ;; try to access it directly
+      (if (empty? deps)
```
Comment (vemv) [inline src/orchard/xref.clj:69]: What if it's just a defn with no deps?

e.g. some new code I'm just writing now.

Comment (Cyrik) [reply src/orchard/xref.clj:69]: then fn-deps-class will still return an empty set, we just waste some time by calling it twice.
the other option would be to run the filter outside the transducer to check if it returns empty. that would mean we don't have to run fn-deps-class twice for empty functions.
In the end, running fn-deps-class twice on empty functions doesn't really make much of a difference since it's very fast, especially when it doesn't have anything to return.

File: test/orchard/xref_test.clj [hunk 2]
```diff
@@ -24,7 +24,10 @@
   (testing "with a symbol"
     (is (= (xref/fn-deps 'orchard.xref-test/dummy-fn)
```
Comment (vemv) [inline test/orchard/xref_test.clj:25]: Swap order of = hands please, normally it's `= <expected> <actual>`

File: src/orchard/xref.clj (hunk 1 above)
Comment (vemv) [reply src/orchard/xref.clj:69]: Alright then!

File: test/orchard/xref_test.clj [hunk 3]
```diff
@@ -52,7 +55,7 @@
   (testing "basics"
     (let [expected #{#'orchard.xref-test/fn-deps-test #'orchard.xref-test/fn-dep #'clojure.core/even?
                      #'clojure.core/filter #'orchard.xref-test/fn-transitive-dep #'clojure.core/map
-                     #'clojure.test/test-var #'clojure.core/range}]
+                     #'clojure.test/test-var #'clojure.core/range #'clojure.core/inc'}]
```
Comment (vemv) [inline test/orchard/xref_test.clj:58]: It would help me to understand, why is `inc'` returned now and not before?

Aren't both `#'clojure.core/range` and `#'clojure.core/inc'` aot-compiled?

Comment (Cyrik) [reply test/orchard/xref_test.clj:58]: That's one of the non-static functions in core, like `conj`. It gets called by `range` as you said, but only the 0 arity version. 
The interesting thing is that inc' has an `:inline` meta but because it doesn't call the function, just passes it to `iterate` it actually does it with the var.

There are two new learnings here: inline dependencies get found if they are just passed along, which does make sense and we always return all arity dependencies. I don't think we can fix the arity thing.

It might make sense to check in with Alex Miller at some point to see if he would be willing to make some modifications to the clojure compiler to make these reflection type things easier and more accurate.

Comment (vemv) [reply test/orchard/xref_test.clj:58]: Thanks!

Please simply add a more explicit test just like a past one:

image

so that we can remember the special meaning inc' has here.

**Comment by vemv** [comment]
Thanks!
