### PR TITLE
[Fix #53] Have info resolve vars before aliases

### LINKED ISSUE #53: orchard.info/info ignores namespace in qualified symbol (0.5.0-beta4)
## Expected behavior

```clj
(ns foo.core
  (:require clojure.string
            [orchard.info :as info]))

(defn -main []
  (clojure.pprint/pprint
   (info/info 'foo.core 'clojure.string/replace)))
```

The above code should print `clojure.string/replace` information.

## Actual behavior

0.5.0-beta3:
```
{:ns #object[clojure.lang.Namespace 0x5fef2aac "clojure.string"],
 :name replace,
 :doc
 "Replaces all instance of match with replacement in s.\n\n   match/replacement can be:\n\n   string / string\n   char / char\n   pattern / (string or function of match).\n\n   See also replace-first.\n\n   The replacement is literal (i.e. none of its characters are treated\n   specially) for all cases above except pattern / string.\n\n   For pattern / string, $1, $2, etc. in the replacement string are\n
  substituted with the string that matched the corresponding\n   parenthesized group in the pattern.  If you wish your replacement\n   string r to be used literally, use (re-quote-replacement r) as the\n
  replacement argument.  See also documentation for\n   java.util.regex.Matcher's appendReplacement method.\n\n   Example:\n   (clojure.string/replace \"Almost Pig Latin\" #\"\\b(\\w)(\\w+)\\b\" \"$2$1ay\")\n   -> \"lmostAay igPay atinLay\"",
 :file "clojure/string.clj",
 :arglists ([s match replacement]),
 :line 75,
 :column 1,
 :added "1.2"}
```

0.5.0-beta4:
```
{:added "1.0",
 :ns clojure.core,
 :name replace,
 :file "clojure/core.clj",
 :static true,
 :column 1,
 :line 5058,
 :arglists ([smap] [smap coll]),
 :see-also
 (clojure.walk/prewalk-replace
  clojure.walk/postwalk-replace
  clojure.core/map
  clojure.string/replace),
 :doc
 "Given a map of replacement pairs and a vector/collection, returns a\n  vector/seq with any elements = a key in smap replaced with the\n  corresponding val in smap.  Returns a transducer when no collection\n  is provided."}
```

## Steps to reproduce the problem

Run the above code.

`project.clj` is here.
```clj
(defproject foo "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.0"]
                 [cider/orchard
                  ;; "0.5.0-beta3"
                  "0.5.0-beta4"]]
  :repl-options {:init-ns foo.core}
  :main foo.core)
```

## Environment & Version information

0.5.0-beta3 and beta4

### Clojure version

1.10.0

### Java version

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

### Operating system

macOS High Sierra

### PR DESCRIPTION
**Pull request by arichiardi**
The info function was resolving aliases, using the unqualified name, before
resolving vars. This was a problem and it has been fixed with this patch.

Before submitting a PR make sure the following things have been done:

- [X] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [X] You've added tests to cover your change(s)
- [X] All tests are passing

### CODE REVIEW

**Comment by arichiardi** [comment]
The test failure is not related to this fix

File: test/orchard/info_test.clj [hunk 1]
```diff
@@ -115,6 +115,23 @@
           (is (= expected (select-keys i [:ns :name :arglists])))
           (is (str/includes? (:file i) "test_ns_dep")))))))
 
+(deftest info-bug-53-test
```
Comment (bbatsov) [inline test/orchard/info_test.clj]: I'd go with more descriptive names here. :-)

File: test/orchard/info_test.clj [hunk 2]
```diff
@@ -115,6 +115,23 @@
...
+  (testing "test for bug #53"
+    (let [expected '{:ns clojure.string
+                     :name replace
+                     :arglists ([s match replacement])}]
+      (testing "- :cljs"
+        (let [i (info/info 'orchard.test-ns 'clojure.string/replace *cljs-params*)]
+          (is (= expected (-> (info/info 'orchard.test-ns 'clojure.string/replace *cljs-params*)
+                              (select-keys [:ns :name :arglists]))))
+          (is (str/starts-with? (:doc i) "Replaces all instance of match with replacement in s."))))
```
Comment (bbatsov) [inline test/orchard/info_test.clj]: I think checking that doc makes the test a bit brittle, as the docstring might be improved in future version of Clojure. Not a huge concern but such checks caused issues in the past.

Comment (arichiardi) [reply test/orchard/info_test.clj]: Ok I will take it away

**Comment by bbatsov** [comment]
Thanks!
